version: '3'

services:
  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - voluem-wordpress:/var/www/wordpress
      
  wordpress:
    container_name: wordpress
    build: 
      context: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"
    restart: on-failure
    volumes:
      - voluem-wordpress:/var/www/wordpress

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "3306"
    restart: unless-stopped
    volumes:
      - voluem-mariadb:/var/lib/mysql

volumes:
  voluem-wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/bperron/inception/data/wordpress'
  voluem-mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/Users/bperron/inception/data/mariadb'

networks:
  inception:
    driver: bridge
